### ISSUE TITLE
AWS IVS chat token parsing issue

### ISSUE THREAD

**Issue by dev1play** [aws-samples/amazon-ivs-chat-web-demo#11]
We are following the official documentation to implement aws ivs chat, live stream video working fine, but ivs chat not working, it shows "Waiting to connect..." and in console we are receiving this error:
"Room a8e912c3-a2ac-4f43-a93c-474e3a0ec0b2 connection did receive error while fetching token ParsingError: expected object but got undefined: undefined"

![image](https://github.com/aws-samples/amazon-ivs-chat-web-demo/assets/89702958/d38a89e6-f53c-4dda-9743-929cc10322ac)

Our web-ui config.js look like this:

export const PLAYBACK_URL = "https://760b256a3da8.us-east-1.playback.live-video.net/api/video/v1/us-east-1.049054135175.channel.6tM2Z9kY16nH.m3u8";

// Chat websocket address
// The AWS region that your room is created in. For example, `us-west-2`.
export const CHAT_REGION = "us-west-2";

// Chat API URL
// The Amazon IVS Chat backend endpoint. You must deploy the serverless backend to get this value.
export const API_URL = "http://localhost:3000/";

// Chat room id (ARN)
export const CHAT_ROOM_ID = "N2K89H7Hd70b";

We have installed docker and running serverless with SAM-CLI

Please let us know any possible solution for this issue.

**Comment by recursivecodes** [comment]
Your chat room ID must be a valid IVS chat room ARN. Please check the format and make sure you copy and paste it completely. 

https://docs.aws.amazon.com/IAM/latest/UserGuide/reference-arns.html
