### ISSUE TITLE
CORS problem AWS IVS

### ISSUE THREAD

**Issue by weasel-v-dev** [aws-samples/amazon-ivs-chat-web-demo#12]
Hello)

I started launching the ivschat  application 

and I got a problem with CORS when I have launched react application

Access to XMLHttpRequest at 'https://3s1sqcr894.execute-api.us-west-2.amazonaws.com/Prod/auth' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

![image](https://github.com/aws-samples/amazon-ivs-chat-web-demo/assets/46993424/fc613d74-9b70-4118-bc5b-94ed0d2e25a1)

this is my config.js

export const PLAYBACK_URL = "https://760b256a3da8.us-east-1.playback.live-video.net/api/video/v1/us-east-1.049054135175.channel.6tM2Z9kY16nH.m3u8";

// Chat websocket address
// The AWS region that your room is created in. For example, `us-west-2`.
export const CHAT_REGION = "us-west-2";

// Chat API URL
// The Amazon IVS Chat backend endpoint. You must deploy the serverless backend to get this value.
export const API_URL = "https://3s1sqcr894.execute-api.us-west-2.amazonaws.com/Prod";

// Chat room id (ARN)
export const CHAT_ROOM_ID = "arn:aws:ivschat:us-west-2:905418016092:room/Qo8vTr8KPhhg";

could you please help me with it?

**Comment by slee-aws** [comment]
@weasel-v-dev I'm sorry to hear you're having this issue. Could you confirm that your `API_URL` is correct? 

Currently, I see that the host `3s1sqcr894.execute-api.us-west-2.amazonaws.com` cannot be resolved.

```
curl -X "POST" "https://3s1sqcr894.execute-api.us-west-2.amazonaws.com/Prod/auth" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "capabilities": [
    "SEND_MESSAGE"
  ],
  "arn": "arn:aws:ivschat:us-west-2:298083573632:room/6O69ZtuABZtu",
  "durationInMinutes": 1,
  "userId": "Sang.50627953-cf0c-40e7-a4d7-6647345a526b",
  "attributes": {
    "avatar": "https://d39ii5l128t5ul.cloudfront.net/assets/animals_square/bird2.png",
    "username": "Sang"
  }
}'
curl: (6) Could not resolve host: 3s1sqcr894.execute-api.us-west-2.amazonaws.com
```
