### ISSUE TITLE
Node 12.x runtime depreciated

### ISSUE THREAD

**Issue by janssenivo** [aws-samples/amazon-ivs-chat-web-demo#7]
The "serverless" solution uses a node.js 12 runtime for Lambda, but node.js 12 has been [deprecated by AWS on Mar 31, 2023](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html). As a result, the SAM package doesn't deploy as it fails with a Cloudformation error:

`CREATE_FAILED  chatEventFunction             Resource handler returned message: "The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions...."`

**Comment by slee-aws** [comment]
Resolved in https://github.com/aws-samples/amazon-ivs-chat-web-demo/pull/8. Thank you for reporting and fixing this issue!
